//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../../../ch1lam/autocv/internal/app/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "workflow.stage.updated": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = app$0.WorkflowStageEvent.createFrom;

configure();
