// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Analyze(rawText: string): $CancellablePromise<$models.JDWorkspace> {
    return $Call.ByID(3208455878, rawText).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetWorkspace(): $CancellablePromise<$models.JDWorkspace> {
    return $Call.ByID(2908750323).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveDraft(rawText: string): $CancellablePromise<$models.JDWorkspace> {
    return $Call.ByID(99189054, rawText).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.JDWorkspace.createFrom;
