// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Analyze(): $CancellablePromise<$models.MatchReview> {
    return $Call.ByID(2909233893).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetReview(): $CancellablePromise<$models.MatchReview> {
    return $Call.ByID(2254571489).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveScope(mode: string, documentIDs: string[]): $CancellablePromise<$models.MatchReview> {
    return $Call.ByID(1256379586, mode, documentIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MatchReview.createFrom;
