// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HealthStatus {
    "application": string;
    "status": string;

    /** Creates a new HealthStatus instance. */
    constructor($$source: Partial<HealthStatus> = {}) {
        if (!("application" in $$source)) {
            this["application"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthStatus($$parsedSource as Partial<HealthStatus>);
    }
}
