// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class EvidenceSourceSummary {
    "chunkId": string;
    "documentId": string;
    "documentName": string;
    "chunkText": string;
    "locatorJson": string;
    "quoteStart": number;
    "quoteEnd": number;

    /** Creates a new EvidenceSourceSummary instance. */
    constructor($$source: Partial<EvidenceSourceSummary> = {}) {
        if (!("chunkId" in $$source)) {
            this["chunkId"] = "";
        }
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }
        if (!("documentName" in $$source)) {
            this["documentName"] = "";
        }
        if (!("chunkText" in $$source)) {
            this["chunkText"] = "";
        }
        if (!("locatorJson" in $$source)) {
            this["locatorJson"] = "";
        }
        if (!("quoteStart" in $$source)) {
            this["quoteStart"] = 0;
        }
        if (!("quoteEnd" in $$source)) {
            this["quoteEnd"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EvidenceSourceSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): EvidenceSourceSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EvidenceSourceSummary($$parsedSource as Partial<EvidenceSourceSummary>);
    }
}

export class EvidenceSummary {
    "id": string;
    "kind": string;
    "title": string;
    "content": string;
    "confidence": number;
    "userVerified": boolean;
    "updatedAt": string;
    "conflictEvidenceIds": string[];
    "sources": EvidenceSourceSummary[];

    /** Creates a new EvidenceSummary instance. */
    constructor($$source: Partial<EvidenceSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("userVerified" in $$source)) {
            this["userVerified"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("conflictEvidenceIds" in $$source)) {
            this["conflictEvidenceIds"] = [];
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EvidenceSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): EvidenceSummary {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflictEvidenceIds" in $$parsedSource) {
            $$parsedSource["conflictEvidenceIds"] = $$createField7_0($$parsedSource["conflictEvidenceIds"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField8_0($$parsedSource["sources"]);
        }
        return new EvidenceSummary($$parsedSource as Partial<EvidenceSummary>);
    }
}

export class ExportResult {
    "cancelled": boolean;
    "kind": string;
    "path": string;

    /** Creates a new ExportResult instance. */
    constructor($$source: Partial<ExportResult> = {}) {
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult($$parsedSource as Partial<ExportResult>);
    }
}

export class HealthStatus {
    "application": string;
    "status": string;

    /** Creates a new HealthStatus instance. */
    constructor($$source: Partial<HealthStatus> = {}) {
        if (!("application" in $$source)) {
            this["application"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthStatus($$parsedSource as Partial<HealthStatus>);
    }
}

export class ImportMarkdownResult {
    "cancelled": boolean;
    "duplicate": boolean;
    "document": SourceDocumentSummary;
    "chunkCount": number;
    "evidenceCount": number;
    "mergedEvidenceCount": number;
    "conflictEvidenceCount": number;
    "warnings": string[];

    /** Creates a new ImportMarkdownResult instance. */
    constructor($$source: Partial<ImportMarkdownResult> = {}) {
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }
        if (!("duplicate" in $$source)) {
            this["duplicate"] = false;
        }
        if (!("document" in $$source)) {
            this["document"] = (new SourceDocumentSummary());
        }
        if (!("chunkCount" in $$source)) {
            this["chunkCount"] = 0;
        }
        if (!("evidenceCount" in $$source)) {
            this["evidenceCount"] = 0;
        }
        if (!("mergedEvidenceCount" in $$source)) {
            this["mergedEvidenceCount"] = 0;
        }
        if (!("conflictEvidenceCount" in $$source)) {
            this["conflictEvidenceCount"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMarkdownResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMarkdownResult {
        const $$createField2_0 = $$createType3;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("document" in $$parsedSource) {
            $$parsedSource["document"] = $$createField2_0($$parsedSource["document"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new ImportMarkdownResult($$parsedSource as Partial<ImportMarkdownResult>);
    }
}

export class JDAnalysisSummary {
    "role": string;
    "company": string;
    "level": string;
    "language": string;
    "responsibilities": JDRequirementSummary[];
    "requiredSkills": JDRequirementSummary[];
    "preferredSkills": JDRequirementSummary[];
    "domainSignals": string[];
    "screeningConstraints": string[];
    "ambiguities": string[];

    /** Creates a new JDAnalysisSummary instance. */
    constructor($$source: Partial<JDAnalysisSummary> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("responsibilities" in $$source)) {
            this["responsibilities"] = [];
        }
        if (!("requiredSkills" in $$source)) {
            this["requiredSkills"] = [];
        }
        if (!("preferredSkills" in $$source)) {
            this["preferredSkills"] = [];
        }
        if (!("domainSignals" in $$source)) {
            this["domainSignals"] = [];
        }
        if (!("screeningConstraints" in $$source)) {
            this["screeningConstraints"] = [];
        }
        if (!("ambiguities" in $$source)) {
            this["ambiguities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JDAnalysisSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): JDAnalysisSummary {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("responsibilities" in $$parsedSource) {
            $$parsedSource["responsibilities"] = $$createField4_0($$parsedSource["responsibilities"]);
        }
        if ("requiredSkills" in $$parsedSource) {
            $$parsedSource["requiredSkills"] = $$createField5_0($$parsedSource["requiredSkills"]);
        }
        if ("preferredSkills" in $$parsedSource) {
            $$parsedSource["preferredSkills"] = $$createField6_0($$parsedSource["preferredSkills"]);
        }
        if ("domainSignals" in $$parsedSource) {
            $$parsedSource["domainSignals"] = $$createField7_0($$parsedSource["domainSignals"]);
        }
        if ("screeningConstraints" in $$parsedSource) {
            $$parsedSource["screeningConstraints"] = $$createField8_0($$parsedSource["screeningConstraints"]);
        }
        if ("ambiguities" in $$parsedSource) {
            $$parsedSource["ambiguities"] = $$createField9_0($$parsedSource["ambiguities"]);
        }
        return new JDAnalysisSummary($$parsedSource as Partial<JDAnalysisSummary>);
    }
}

export class JDRequirementSummary {
    "id": string;
    "text": string;
    "importance": number;
    "hardConstraint": boolean;

    /** Creates a new JDRequirementSummary instance. */
    constructor($$source: Partial<JDRequirementSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("importance" in $$source)) {
            this["importance"] = 0;
        }
        if (!("hardConstraint" in $$source)) {
            this["hardConstraint"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JDRequirementSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): JDRequirementSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JDRequirementSummary($$parsedSource as Partial<JDRequirementSummary>);
    }
}

export class JDWorkspace {
    "id": string;
    "title": string;
    "company": string;
    "rawText": string;
    "language": string;
    "analysisStatus": string;
    "analysisError": string;
    "updatedAt": string;
    "warnings": string[];
    "analysis": JDAnalysisSummary | null;

    /** Creates a new JDWorkspace instance. */
    constructor($$source: Partial<JDWorkspace> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("rawText" in $$source)) {
            this["rawText"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("analysisStatus" in $$source)) {
            this["analysisStatus"] = "";
        }
        if (!("analysisError" in $$source)) {
            this["analysisError"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("analysis" in $$source)) {
            this["analysis"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JDWorkspace instance from a string or object.
     */
    static createFrom($$source: any = {}): JDWorkspace {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField8_0($$parsedSource["warnings"]);
        }
        if ("analysis" in $$parsedSource) {
            $$parsedSource["analysis"] = $$createField9_0($$parsedSource["analysis"]);
        }
        return new JDWorkspace($$parsedSource as Partial<JDWorkspace>);
    }
}

export class MatchCounts {
    "strong": number;
    "partial": number;
    "missing": number;
    "unknown": number;

    /** Creates a new MatchCounts instance. */
    constructor($$source: Partial<MatchCounts> = {}) {
        if (!("strong" in $$source)) {
            this["strong"] = 0;
        }
        if (!("partial" in $$source)) {
            this["partial"] = 0;
        }
        if (!("missing" in $$source)) {
            this["missing"] = 0;
        }
        if (!("unknown" in $$source)) {
            this["unknown"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchCounts instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchCounts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatchCounts($$parsedSource as Partial<MatchCounts>);
    }
}

export class MatchDimensionSummary {
    "category": string;
    "label": string;
    "weight": number;
    "earned": number;
    "requirementCount": number;

    /** Creates a new MatchDimensionSummary instance. */
    constructor($$source: Partial<MatchDimensionSummary> = {}) {
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("weight" in $$source)) {
            this["weight"] = 0;
        }
        if (!("earned" in $$source)) {
            this["earned"] = 0;
        }
        if (!("requirementCount" in $$source)) {
            this["requirementCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchDimensionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchDimensionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatchDimensionSummary($$parsedSource as Partial<MatchDimensionSummary>);
    }
}

export class MatchEvidenceSourceSummary {
    "chunkId": string;
    "documentId": string;
    "documentName": string;
    "chunkText": string;
    "locatorJson": string;
    "quoteStart": number;
    "quoteEnd": number;

    /** Creates a new MatchEvidenceSourceSummary instance. */
    constructor($$source: Partial<MatchEvidenceSourceSummary> = {}) {
        if (!("chunkId" in $$source)) {
            this["chunkId"] = "";
        }
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }
        if (!("documentName" in $$source)) {
            this["documentName"] = "";
        }
        if (!("chunkText" in $$source)) {
            this["chunkText"] = "";
        }
        if (!("locatorJson" in $$source)) {
            this["locatorJson"] = "";
        }
        if (!("quoteStart" in $$source)) {
            this["quoteStart"] = 0;
        }
        if (!("quoteEnd" in $$source)) {
            this["quoteEnd"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchEvidenceSourceSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchEvidenceSourceSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatchEvidenceSourceSummary($$parsedSource as Partial<MatchEvidenceSourceSummary>);
    }
}

export class MatchEvidenceSummary {
    "id": string;
    "kind": string;
    "title": string;
    "content": string;
    "sources": MatchEvidenceSourceSummary[];

    /** Creates a new MatchEvidenceSummary instance. */
    constructor($$source: Partial<MatchEvidenceSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchEvidenceSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchEvidenceSummary {
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField4_0($$parsedSource["sources"]);
        }
        return new MatchEvidenceSummary($$parsedSource as Partial<MatchEvidenceSummary>);
    }
}

export class MatchReview {
    "status": string;
    "message": string;
    "error": string;
    "jdTitle": string;
    "company": string;
    "totalScore": number;
    "hardCapApplied": boolean;
    "updatedAt": string;
    "counts": MatchCounts;
    "dimensions": MatchDimensionSummary[];
    "requirements": RequirementMatchSummary[];
    "scope": RunScopeSummary;

    /** Creates a new MatchReview instance. */
    constructor($$source: Partial<MatchReview> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("jdTitle" in $$source)) {
            this["jdTitle"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("totalScore" in $$source)) {
            this["totalScore"] = 0;
        }
        if (!("hardCapApplied" in $$source)) {
            this["hardCapApplied"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("counts" in $$source)) {
            this["counts"] = (new MatchCounts());
        }
        if (!("dimensions" in $$source)) {
            this["dimensions"] = [];
        }
        if (!("requirements" in $$source)) {
            this["requirements"] = [];
        }
        if (!("scope" in $$source)) {
            this["scope"] = (new RunScopeSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchReview instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchReview {
        const $$createField8_0 = $$createType10;
        const $$createField9_0 = $$createType12;
        const $$createField10_0 = $$createType14;
        const $$createField11_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("counts" in $$parsedSource) {
            $$parsedSource["counts"] = $$createField8_0($$parsedSource["counts"]);
        }
        if ("dimensions" in $$parsedSource) {
            $$parsedSource["dimensions"] = $$createField9_0($$parsedSource["dimensions"]);
        }
        if ("requirements" in $$parsedSource) {
            $$parsedSource["requirements"] = $$createField10_0($$parsedSource["requirements"]);
        }
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField11_0($$parsedSource["scope"]);
        }
        return new MatchReview($$parsedSource as Partial<MatchReview>);
    }
}

export class PDFWorkspace {
    "status": string;
    "message": string;
    "exportIssues": string[];
    "artifactId": string;
    "resumeId": string;
    "version": number;
    "language": string;
    "targetRole": string;
    "renderedAt": string;
    "contentHash": string;
    "pdfBase64": string;
    "previewPagesBase64": string[];
    "canExport": boolean;

    /** Creates a new PDFWorkspace instance. */
    constructor($$source: Partial<PDFWorkspace> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("exportIssues" in $$source)) {
            this["exportIssues"] = [];
        }
        if (!("artifactId" in $$source)) {
            this["artifactId"] = "";
        }
        if (!("resumeId" in $$source)) {
            this["resumeId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("targetRole" in $$source)) {
            this["targetRole"] = "";
        }
        if (!("renderedAt" in $$source)) {
            this["renderedAt"] = "";
        }
        if (!("contentHash" in $$source)) {
            this["contentHash"] = "";
        }
        if (!("pdfBase64" in $$source)) {
            this["pdfBase64"] = "";
        }
        if (!("previewPagesBase64" in $$source)) {
            this["previewPagesBase64"] = [];
        }
        if (!("canExport" in $$source)) {
            this["canExport"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PDFWorkspace instance from a string or object.
     */
    static createFrom($$source: any = {}): PDFWorkspace {
        const $$createField2_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exportIssues" in $$parsedSource) {
            $$parsedSource["exportIssues"] = $$createField2_0($$parsedSource["exportIssues"]);
        }
        if ("previewPagesBase64" in $$parsedSource) {
            $$parsedSource["previewPagesBase64"] = $$createField11_0($$parsedSource["previewPagesBase64"]);
        }
        return new PDFWorkspace($$parsedSource as Partial<PDFWorkspace>);
    }
}

export class ProfileOverview {
    "profileId": string;
    "name": string;
    "defaultLanguage": string;
    "profiles": ProfileSummary[];
    "documents": SourceDocumentSummary[];
    "evidence": EvidenceSummary[];

    /** Creates a new ProfileOverview instance. */
    constructor($$source: Partial<ProfileOverview> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("defaultLanguage" in $$source)) {
            this["defaultLanguage"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }
        if (!("documents" in $$source)) {
            this["documents"] = [];
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileOverview {
        const $$createField3_0 = $$createType17;
        const $$createField4_0 = $$createType18;
        const $$createField5_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField3_0($$parsedSource["profiles"]);
        }
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField4_0($$parsedSource["documents"]);
        }
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField5_0($$parsedSource["evidence"]);
        }
        return new ProfileOverview($$parsedSource as Partial<ProfileOverview>);
    }
}

export class ProfileSearchResult {
    "entityType": string;
    "entityId": string;
    "documentId": string;
    "sourceChunkId": string;
    "documentName": string;
    "title": string;
    "snippet": string;

    /** Creates a new ProfileSearchResult instance. */
    constructor($$source: Partial<ProfileSearchResult> = {}) {
        if (!("entityType" in $$source)) {
            this["entityType"] = "";
        }
        if (!("entityId" in $$source)) {
            this["entityId"] = "";
        }
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }
        if (!("sourceChunkId" in $$source)) {
            this["sourceChunkId"] = "";
        }
        if (!("documentName" in $$source)) {
            this["documentName"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("snippet" in $$source)) {
            this["snippet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSearchResult($$parsedSource as Partial<ProfileSearchResult>);
    }
}

export class ProfileSummary {
    "id": string;
    "name": string;
    "defaultLanguage": string;
    "active": boolean;

    /** Creates a new ProfileSummary instance. */
    constructor($$source: Partial<ProfileSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("defaultLanguage" in $$source)) {
            this["defaultLanguage"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSummary($$parsedSource as Partial<ProfileSummary>);
    }
}

export class ProviderCancelResult {
    "cancelled": boolean;
    "task": string;
    "message": string;

    /** Creates a new ProviderCancelResult instance. */
    constructor($$source: Partial<ProviderCancelResult> = {}) {
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderCancelResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderCancelResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderCancelResult($$parsedSource as Partial<ProviderCancelResult>);
    }
}

export class ProviderDataSummary {
    "label": string;
    "description": string;

    /** Creates a new ProviderDataSummary instance. */
    constructor($$source: Partial<ProviderDataSummary> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderDataSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderDataSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderDataSummary($$parsedSource as Partial<ProviderDataSummary>);
    }
}

export class ProviderSettings {
    "provider": string;
    "baseUrl": string;
    "model": string;
    "apiKeyConfigured": boolean;
    "secretBackend": string;
    "sentContentTypes": ProviderDataSummary[];
    "localOnlyTypes": ProviderDataSummary[];
    "configurationNote": string;
    "updatedAt": string;

    /** Creates a new ProviderSettings instance. */
    constructor($$source: Partial<ProviderSettings> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("apiKeyConfigured" in $$source)) {
            this["apiKeyConfigured"] = false;
        }
        if (!("secretBackend" in $$source)) {
            this["secretBackend"] = "";
        }
        if (!("sentContentTypes" in $$source)) {
            this["sentContentTypes"] = [];
        }
        if (!("localOnlyTypes" in $$source)) {
            this["localOnlyTypes"] = [];
        }
        if (!("configurationNote" in $$source)) {
            this["configurationNote"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderSettings {
        const $$createField5_0 = $$createType22;
        const $$createField6_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sentContentTypes" in $$parsedSource) {
            $$parsedSource["sentContentTypes"] = $$createField5_0($$parsedSource["sentContentTypes"]);
        }
        if ("localOnlyTypes" in $$parsedSource) {
            $$parsedSource["localOnlyTypes"] = $$createField6_0($$parsedSource["localOnlyTypes"]);
        }
        return new ProviderSettings($$parsedSource as Partial<ProviderSettings>);
    }
}

export class RequirementMatchSummary {
    "id": string;
    "category": string;
    "group": string;
    "text": string;
    "importance": number;
    "hardConstraint": boolean;
    "strength": string;
    "explanation": string;
    "clarificationNeeded": boolean;
    "evidence": MatchEvidenceSummary[];

    /** Creates a new RequirementMatchSummary instance. */
    constructor($$source: Partial<RequirementMatchSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("importance" in $$source)) {
            this["importance"] = 0;
        }
        if (!("hardConstraint" in $$source)) {
            this["hardConstraint"] = false;
        }
        if (!("strength" in $$source)) {
            this["strength"] = "";
        }
        if (!("explanation" in $$source)) {
            this["explanation"] = "";
        }
        if (!("clarificationNeeded" in $$source)) {
            this["clarificationNeeded"] = false;
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequirementMatchSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): RequirementMatchSummary {
        const $$createField9_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField9_0($$parsedSource["evidence"]);
        }
        return new RequirementMatchSummary($$parsedSource as Partial<RequirementMatchSummary>);
    }
}

export class ResumeBlockSummary {
    "id": string;
    "kind": string;
    "label": string;
    "content": string;
    "locked": boolean;
    "groundingLevel": string;
    "optimization": string;
    "evidence": MatchEvidenceSummary[];

    /** Creates a new ResumeBlockSummary instance. */
    constructor($$source: Partial<ResumeBlockSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("groundingLevel" in $$source)) {
            this["groundingLevel"] = "";
        }
        if (!("optimization" in $$source)) {
            this["optimization"] = "";
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResumeBlockSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ResumeBlockSummary {
        const $$createField7_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField7_0($$parsedSource["evidence"]);
        }
        return new ResumeBlockSummary($$parsedSource as Partial<ResumeBlockSummary>);
    }
}

export class ResumeWorkspace {
    "status": string;
    "message": string;
    "canExport": boolean;
    "exportIssues": string[];
    "runId": string;
    "resumeId": string;
    "version": number;
    "language": string;
    "targetRole": string;
    "packagingLevel": number;
    "packagingLabel": string;
    "markdown": string;
    "updatedAt": string;
    "optimizationNotes": string[];
    "blocks": ResumeBlockSummary[];

    /** Creates a new ResumeWorkspace instance. */
    constructor($$source: Partial<ResumeWorkspace> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("canExport" in $$source)) {
            this["canExport"] = false;
        }
        if (!("exportIssues" in $$source)) {
            this["exportIssues"] = [];
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("resumeId" in $$source)) {
            this["resumeId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("targetRole" in $$source)) {
            this["targetRole"] = "";
        }
        if (!("packagingLevel" in $$source)) {
            this["packagingLevel"] = 0;
        }
        if (!("packagingLabel" in $$source)) {
            this["packagingLabel"] = "";
        }
        if (!("markdown" in $$source)) {
            this["markdown"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("optimizationNotes" in $$source)) {
            this["optimizationNotes"] = [];
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResumeWorkspace instance from a string or object.
     */
    static createFrom($$source: any = {}): ResumeWorkspace {
        const $$createField3_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exportIssues" in $$parsedSource) {
            $$parsedSource["exportIssues"] = $$createField3_0($$parsedSource["exportIssues"]);
        }
        if ("optimizationNotes" in $$parsedSource) {
            $$parsedSource["optimizationNotes"] = $$createField13_0($$parsedSource["optimizationNotes"]);
        }
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField14_0($$parsedSource["blocks"]);
        }
        return new ResumeWorkspace($$parsedSource as Partial<ResumeWorkspace>);
    }
}

export class RunScopeDocumentSummary {
    "id": string;
    "originalName": string;
    "kind": string;
    "selected": boolean;

    /** Creates a new RunScopeDocumentSummary instance. */
    constructor($$source: Partial<RunScopeDocumentSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("originalName" in $$source)) {
            this["originalName"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunScopeDocumentSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): RunScopeDocumentSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunScopeDocumentSummary($$parsedSource as Partial<RunScopeDocumentSummary>);
    }
}

export class RunScopeSummary {
    "mode": string;
    "selectedCount": number;
    "availableCount": number;
    "selectedDocumentIds": string[];
    "documents": RunScopeDocumentSummary[];

    /** Creates a new RunScopeSummary instance. */
    constructor($$source: Partial<RunScopeSummary> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("selectedCount" in $$source)) {
            this["selectedCount"] = 0;
        }
        if (!("availableCount" in $$source)) {
            this["availableCount"] = 0;
        }
        if (!("selectedDocumentIds" in $$source)) {
            this["selectedDocumentIds"] = [];
        }
        if (!("documents" in $$source)) {
            this["documents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunScopeSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): RunScopeSummary {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selectedDocumentIds" in $$parsedSource) {
            $$parsedSource["selectedDocumentIds"] = $$createField3_0($$parsedSource["selectedDocumentIds"]);
        }
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField4_0($$parsedSource["documents"]);
        }
        return new RunScopeSummary($$parsedSource as Partial<RunScopeSummary>);
    }
}

export class SaveEvidenceInput {
    "evidenceId": string;
    "title": string;
    "content": string;
    "userVerified": boolean;

    /** Creates a new SaveEvidenceInput instance. */
    constructor($$source: Partial<SaveEvidenceInput> = {}) {
        if (!("evidenceId" in $$source)) {
            this["evidenceId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("userVerified" in $$source)) {
            this["userVerified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveEvidenceInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveEvidenceInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveEvidenceInput($$parsedSource as Partial<SaveEvidenceInput>);
    }
}

export class SaveProviderInput {
    "provider": string;
    "baseUrl": string;
    "model": string;
    "apiKey": string;

    /** Creates a new SaveProviderInput instance. */
    constructor($$source: Partial<SaveProviderInput> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveProviderInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveProviderInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveProviderInput($$parsedSource as Partial<SaveProviderInput>);
    }
}

export class SourceDocumentSummary {
    "id": string;
    "originalName": string;
    "kind": string;
    "parseStatus": string;
    "importedAt": string;

    /** Creates a new SourceDocumentSummary instance. */
    constructor($$source: Partial<SourceDocumentSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("originalName" in $$source)) {
            this["originalName"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("parseStatus" in $$source)) {
            this["parseStatus"] = "";
        }
        if (!("importedAt" in $$source)) {
            this["importedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceDocumentSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceDocumentSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceDocumentSummary($$parsedSource as Partial<SourceDocumentSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = EvidenceSourceSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = SourceDocumentSummary.createFrom;
const $$createType4 = JDRequirementSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = JDAnalysisSummary.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = MatchEvidenceSourceSummary.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = MatchCounts.createFrom;
const $$createType11 = MatchDimensionSummary.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = RequirementMatchSummary.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = RunScopeSummary.createFrom;
const $$createType16 = ProfileSummary.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($$createType3);
const $$createType19 = EvidenceSummary.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = ProviderDataSummary.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = MatchEvidenceSummary.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = ResumeBlockSummary.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = RunScopeDocumentSummary.createFrom;
const $$createType28 = $Create.Array($$createType27);
