// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportMarkdown(): $CancellablePromise<$models.ExportResult> {
    return $Call.ByID(42131739).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExportPDF(): $CancellablePromise<$models.ExportResult> {
    return $Call.ByID(1168273540).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetWorkspace(): $CancellablePromise<$models.PDFWorkspace> {
    return $Call.ByID(3331330353).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Render(): $CancellablePromise<$models.PDFWorkspace> {
    return $Call.ByID(679362808).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExportResult.createFrom;
const $$createType1 = $models.PDFWorkspace.createFrom;
