// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProfile(name: string, defaultLanguage: string): $CancellablePromise<$models.ProfileOverview> {
    return $Call.ByID(1258940892, name, defaultLanguage).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetOverview(): $CancellablePromise<$models.ProfileOverview> {
    return $Call.ByID(2947916482).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportMarkdown(): $CancellablePromise<$models.ImportMarkdownResult> {
    return $Call.ByID(1029681327).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveEvidence(input: $models.SaveEvidenceInput): $CancellablePromise<$models.ProfileOverview> {
    return $Call.ByID(1239655375, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Search(query: string): $CancellablePromise<$models.ProfileSearchResult[]> {
    return $Call.ByID(3916904059, query).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SelectProfile(profileID: string): $CancellablePromise<$models.ProfileOverview> {
    return $Call.ByID(1871072508, profileID).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProfileOverview.createFrom;
const $$createType1 = $models.ImportMarkdownResult.createFrom;
const $$createType2 = $models.ProfileSearchResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
