// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetOverview(): $CancellablePromise<$models.ProfileOverview> {
    return $Call.ByID(2947916482).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportMarkdown(): $CancellablePromise<$models.ImportMarkdownResult> {
    return $Call.ByID(1029681327).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProfileOverview.createFrom;
const $$createType1 = $models.ImportMarkdownResult.createFrom;
