// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Generate(language: string, packagingLevel: number): $CancellablePromise<$models.ResumeWorkspace> {
    return $Call.ByID(3717722824, language, packagingLevel).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetWorkspace(): $CancellablePromise<$models.ResumeWorkspace> {
    return $Call.ByID(1848218154).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetBlockLocked(blockID: string, locked: boolean): $CancellablePromise<$models.ResumeWorkspace> {
    return $Call.ByID(4069260596, blockID, locked).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateMarkdown(markdown: string): $CancellablePromise<$models.ResumeWorkspace> {
    return $Call.ByID(3532077675, markdown).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ResumeWorkspace.createFrom;
