// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.ProviderSettings> {
    return $Call.ByID(2096109326).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveProvider(input: $models.SaveProviderInput): $CancellablePromise<$models.ProviderSettings> {
    return $Call.ByID(424227985, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProviderSettings.createFrom;
